# Generated by Django 4.1.4 on 2022-12-23 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('Tank', 'Танки'), ('Heal', 'Хилы'), ('DD', 'ДД'), ('Trader', 'Торговцы'), ('Guildmasters', 'Гилдмастеры'), ('Quest', 'Квестгиверы'), ('Smith', 'Кузнецы'), ('Tanner', 'Кожевники'), ('Potion', 'Зельевары'), ('Spellmasters', 'Мастера заклинаний')], default='Tank', max_length=16)),
                ('title', models.CharField(max_length=128)),
                ('text', models.TextField()),
                ('upload', models.FileField(upload_to='uploads/')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('commentOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Order.order')),
                ('commentUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
